### ISSUE TITLE
No requirements.txt in the rlaif

### ISSUE THREAD

**Issue by JRestom** [kiddyboots216/lottery-ticket-adaptation#5]
Currently, there's no requirements.txt file in the rlaif folder (as described per instructions in the README)

**Comment by kiddyboots216** [comment]
Thanks! I had .txt files in the gitignore. Pushed the requirements.txt

**Comment by nicosquare** [comment]
Hi, @kiddyboots216!

I have a question: is there an alternative to the requirement: https://github.com/kiddyboots216/alignment-durability.git ?

Thanks in advance!
